set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN G2 [get_ports {sel[7]}]
set_property PACKAGE_PIN C2 [get_ports {sel[6]}]
set_property PACKAGE_PIN C1 [get_ports {sel[5]}]
set_property PACKAGE_PIN H1 [get_ports {sel[4]}]
set_property PACKAGE_PIN G1 [get_ports {sel[3]}]
set_property PACKAGE_PIN F1 [get_ports {sel[2]}]
set_property PACKAGE_PIN E1 [get_ports {sel[1]}]
set_property PACKAGE_PIN G6 [get_ports {sel[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL[0]}]
set_property PACKAGE_PIN B4 [get_ports {LEDL[6]}]
set_property PACKAGE_PIN A4 [get_ports {LEDL[5]}]
set_property PACKAGE_PIN A3 [get_ports {LEDL[4]}]
set_property PACKAGE_PIN B1 [get_ports {LEDL[3]}]
set_property PACKAGE_PIN A1 [get_ports {LEDL[2]}]
set_property PACKAGE_PIN B3 [get_ports {LEDL[1]}]
set_property PACKAGE_PIN B2 [get_ports {LEDL[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDL1[0]}]
set_property PACKAGE_PIN D4 [get_ports {LEDL1[6]}]
set_property PACKAGE_PIN E3 [get_ports {LEDL1[5]}]
set_property PACKAGE_PIN D3 [get_ports {LEDL1[4]}]
set_property PACKAGE_PIN F4 [get_ports {LEDL1[3]}]
set_property PACKAGE_PIN F3 [get_ports {LEDL1[2]}]
set_property PACKAGE_PIN E2 [get_ports {LEDL1[1]}]
set_property PACKAGE_PIN D2 [get_ports {LEDL1[0]}]
